import tkinter
from tkinter import messagebox
app = tkinter.Tk()
def data():
    # v=v1.get()
    # l2.config(text=v)
    # messagebox.showinfo("display",v1.get())
    # messagebox.askokcancel("display",v1.get())
    if v_c1.get()==1:
        print("mal select")
    if v_c2.get()==1:
        print("eng selected")    
    if vr1.get()==1:
        print("male")
    if vr1.get()==2:
        print("female")    
app.title("synnefo")
app.minsize(400,400)
app.maxsize(600,600)
app.config(bg="red")
l1=tkinter.Label(app,text="welcome",bg="red",fg="blue")
l1.pack()
v1=tkinter.StringVar()
e1=tkinter.Entry(app,textvariable=v1)
e1.pack()
v_c1=tkinter.IntVar()
v_c2=tkinter.IntVar()
c1=tkinter.Checkbutton(app,text="mal",variable=v_c1)
c1.pack()
c2=tkinter.Checkbutton(app,text="eng",variable=v_c2)
c2.pack()
vr1=tkinter.IntVar()
r1=tkinter.Radiobutton(app,text="male",value=1,variable=vr1)
r2=tkinter.Radiobutton(app,text="female",value=2,variable=vr1)
r1.pack()
r2.pack()
b1=tkinter.Button(app,text="save",bg="black",fg="white",activebackground="green",activeforeground="red",padx=10,pady=10,command=data)
b1.pack()
l2=tkinter.Label(app)
l2.pack()
app.mainloop()